name: Build Moonlight-QT

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt6-base-dev libqt6svg6-dev libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libopus-dev libsdl2-dev libssl-dev libva-dev libvdpau-dev libxkbcommon-dev libpulse-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-qt-ubuntu
          path: ${{github.workspace}}/build/bin/Moonlight*
