name: Build Moonlight-QT

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libegl1-mesa-dev libgl1-mesa-dev libopus-dev libsdl2-dev libsdl2-ttf-dev \
            libssl-dev libavcodec-dev libavformat-dev libswscale-dev libva-dev \
            libvdpau-dev libxkbcommon-dev wayland-protocols libdrm-dev \
            qt6-base-dev qt6-declarative-dev libqt6svg6-dev qmake6 \
            qml6-module-qtquick-controls qml6-module-qtquick-templates \
            qml6-module-qtquick-layouts qml6-module-qtqml-workerscript \
            qml6-module-qtquick-window qml6-module-qtquick

      - name: Configure and Build
        run: |
          qmake6 moonlight-qt.pro
          make -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-qt-ubuntu
          path: Moonlight
